# Generated by Django 5.1.3 on 2024-11-24 17:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_bill_billitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
