# Generated by Django 5.1.3 on 2024-11-24 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_billitem_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.creditcard'),
        ),
    ]
