# Generated by Django 5.1.3 on 2024-11-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_bill_credit_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='credit_card',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='user',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='user',
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='BasketItem',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='BillItem',
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
